odpocznij/urls.py
from django.contrib import admin
from django.urls import path

from main.views import LandingPageView, MainView, PremisesView, LoginFormView, LogoutView, \
    EditUserView, UserView, ReservationListView, NewReservationView, ClientRegistrationView, EditReservationView, \
    DeleteReservationView, CreateReviewView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('index/', MainView.as_view(), name='main-page'),
    path('index/<int:id>/', PremisesView.as_view(), name='premises'),
    path('user/<int:pk>/reservations/', ReservationListView.as_view(), name='reservations'),
    path('index/<int:id>/new_reservation/', NewReservationView.as_view(), name='new-reservation'),
    path('index/<int:pk>/edit_reservation/', EditReservationView.as_view(), name='edit-reservation'),
    path('index/<int:pk>/delete_reservation/', DeleteReservationView.as_view(), name='delete-reservation'),
    path('index/<int:pk>/reservations/new_review/', CreateReviewView.as_view(), name='new-review'),
    path('client_registration/', ClientRegistrationView.as_view(), name='client-registration'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/<int:pk>/', UserView.as_view(), name='user'),
    path('user/<int:pk>/edit_user/', EditUserView.as_view(), name='edit-user'),
]

main/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField

# Create your models here.

TYPES = [
    ('ZOL', 'Zakład opiekuńczo-leczniczy'),
    ('OR', 'Oddział Rehabilitacji'),
    ('S', 'Sanatorium'),
    ('DPS', 'Dom Pomocy Społecznej'),
    ('DOP', 'Długoterminowa opieka prywatna'),
    ('KOP', 'Krótkoterminowa opieka prywatna'),
]


class Premises(models.Model):
    COUNTRIES_FIRST = ['PL']
    name = models.CharField("Nazwa", max_length=256)
    address = models.CharField("Adres", max_length=1024)
    zip_code = models.CharField("Kod pocztowy", max_length=12)
    city = models.CharField("Miejscowość", max_length=1024)
    country = CountryField()
    type = models.CharField(max_length=32, choices=TYPES)
    description = models.TextField()

    def __str__(self):
        return self.name


class Room(models.Model):
    people_number = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    capacity = models.FloatField(null=True, blank=True)
    premises = models.ForeignKey(Premises, related_name='rooms', on_delete=models.CASCADE)


class Feature(models.Model):
    name = models.CharField(max_length=256)
    rooms = models.ManyToManyField(Room)

    def __str__(self):
        return self.name


class Reservation(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rooms = models.ForeignKey(Room, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('reservation', args=[self.id])


class Review(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    score = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(1)])
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    reservation = models.OneToOneField(Reservation, related_name='review', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    premise = models.ForeignKey(Premises, on_delete=models.CASCADE)

main/forms.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import django.forms as forms

from main.models import Reservation, Review


def username_unique(username):
    if User.objects.filter(username=username):
        raise ValidationError('Login jest zajęty')


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='login', validators=[username_unique])
    password = forms.CharField(label='hasło', widget=forms.PasswordInput)
    second_password = forms.CharField(label='powtórz hasło', widget=forms.PasswordInput)
    first_name = forms.CharField(label='imię')
    last_name = forms.CharField(label='nazwisko')
    email = forms.EmailField(label='email')

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['password'] != cleaned_data['second_password']:
            raise ValidationError("Proszę wprowadzić dwa razy to samo hasło")


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class LoginForm(forms.Form):
    login = forms.CharField(label='login')
    password = forms.CharField(label='hasło', widget=forms.PasswordInput)


class NewReservationForm(forms.ModelForm):
    class Meta:
        labels = {'start_date': 'Data początkowa', 'end_date': 'Data końcowa'}
        model = Reservation
        fields = ['start_date', 'end_date']
        widgets = {'start_date': forms.SelectDateWidget, 'end_date': forms.SelectDateWidget} #można zaimplementować datepicker https://simpleisbetterthancomplex.com/tutorial/2019/01/03/how-to-use-date-picker-with-django.html


class NewReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'score', 'content']
        labels = {'title': 'Tytuł', 'score': 'Ocena', 'content': 'Treść'}

main/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Avg
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from main.forms import UserRegistrationForm, LoginForm, NewReservationForm, UserForm
from main.models import Premises, Reservation, Room, Review


class LandingPageView(View):
    def get(self, request):
        return render(request, 'main/landingpage.html')


class MainView(View):
    def get(self, request):
        search = request.GET.get('search')
        request.session['search'] = search
        results = Premises.objects.all().filter(city=search).annotate(avg_score=Avg('review__score'))
        return render(request, 'main/main.html', {'results': results})


class PremisesView(View):
    def get(self, request, id):
        premises = Premises.objects.get(pk=id)
        room_types = premises.rooms.order_by('people_number')
        return render(request, "main/premises_view.html", {"premises": premises, "room_types": room_types})


class ReservationListView(LoginRequiredMixin, ListView):
    model = Reservation

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class NewReservationView(LoginRequiredMixin, View):
    def get(self, request, id):
        room = Room.objects.get(pk=id)
        form = NewReservationForm()
        return render(request, 'main/reservation_form.html', {'form': form, 'room': room})

    def post(self, request, id):
        room = Room.objects.get(pk=id)
        user = request.user
        form = NewReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            start_date = reservation.start_date
            end_date = reservation.end_date
            case_1 = Reservation.objects.filter(rooms=room, start_date__lte=start_date,
                                                end_date__gte=start_date).exists()
            case_2 = Reservation.objects.filter(rooms=room, start_date__lte=end_date, end_date__gte=end_date).exists()
            case_3 = Reservation.objects.filter(rooms=room, start_date__gte=start_date, end_date__lte=end_date).exists()
            if case_1 or case_2 or case_3:
                return render(request, 'main/reservation_form.html',
                              {'id': room.id, 'form': form, 'room': room,
                               'error': 'Pokój jest zajęty w podanych dniach'})
            reservation.rooms = room
            reservation.user = user
            reservation.save()
            return redirect('reservations', user.id)
        else:
            return render(request, 'main/reservation_form.html', {'form': form})


class EditReservationView(LoginRequiredMixin, UpdateView):
    model = Reservation
    fields = ['start_date', 'end_date']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('reservations', kwargs={'pk': pk})


class DeleteReservationView(LoginRequiredMixin, DeleteView):
    model = Reservation

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('reservations', kwargs={'pk': pk})


class ClientRegistrationView(View):
    def get(self, request):
        form = UserRegistrationForm()
        return render(request, 'main/user_form.html', {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email']
            )
            return redirect('/')
        else:
            return render(request, 'main/user_form.html', {'form': form})


class LoginFormView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'main/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['login'],
                                password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'main/login.html', {'form': form, 'error': 'Brak użytkownika o podanym loginie'})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(request.META['HTTP_REFERER'])


class EditUserView(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = User.objects.get(id=pk)
        form = UserForm(instance=user)
        return render(request, 'main/user_form.html', {'form': form})

    def post(self, request, pk):
        form = UserForm(data=request.POST, instance=request.user)
        if form.is_valid():
            User.objects.filter(pk=pk).update(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email']
            )
            user = User.objects.get(pk=pk)
            return redirect('user', user.id)
        else:
            return render(request, 'main/user_form.html', {'form': form})


class UserView(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        return render(request, 'main/user.html', {'user': user})


class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    fields = ['title', 'score', 'content']

    def form_valid(self, form):
        reservation = Reservation.objects.get(pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        form.instance.reservation = reservation
        form.instance.premise = reservation.rooms.premises
        return super().form_valid(form)

    def get_success_url(self):
        user_id = self.kwargs['pk']
        return reverse_lazy('reservations', kwargs={'pk': user_id})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
<div class="topnav">
    <a class="logo" href="{% url 'landing-page' %}">odpocznij.pl</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Wyloguj</a>
        <a href="{% url 'reservations' user.id %}">Twoje rezerwacje</a>
        <a href="{% url 'user' user.id %}">{{ user.username }}</a>
        {% else %}
        <a href="{% url 'login' %}">Zaloguj się</a> <a href="{% url 'client-registration' %}">Zarejestruj się</a>
    {% endif %}
</div>
<br>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/landingpage.html
<!DOCTYPE html>
<html>
<head>

</head>

{% load static %}
<body class="landingpage">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
<p class="landingpage_logo">odpocznij.pl
<div class="landingpage-searchbar">
    <form action="{% url 'main-page' %}" method="get">
        Podaj miejscowość:
        <input class="text-center" type="text" name="search">
        <input type="submit" value="Szukaj">
    </form>
</div>
</body>

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block content %}
    {{ error }}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="Zaloguj">
    </form>
{% endblock %}

main/templates/main/main.html
{% extends 'main/base.html' %}
{% block content %}
    <h3>{{ results.0.city }}</h3>
    <p>liczba ośrodków: {{ results.count }}
        {% for result in results %}
            <div class="main_search_results">
                <a href="{% url 'premises' result.id %}"> {{ result.get_type_display }} {{ result.name }}</a>
                <br>
                {% if result.avg_score %}
                    <div class="rating">
                        {{ result.avg_score }}
                    </div>
                {% endif %}
                {{ result.address }}
                {{ result.city }}
                <br>{{ result.description }}
            </div>
        {% empty %}
            <p>Brak wyników wyszukiwania
        {% endfor %}
{% endblock %}

main/templates/main/premises_view.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <div class="container">
        <h3>{{ premises.get_type_display }} {{ premises.name }}</h3>
        <br>{{ premises.address }}
        {{ premises.city }}
        <br>{{ premises.description }}
    </div>
    <div class="container">
        <table>
            {% regroup room_types by people_number as room_types_unique %}
            <tr>
                <th>Liczba osób w pokoju</th>
                <th>Udogodnienia</th>
                <th>Cena za osobę za noc</th>
                <th>Rezerwuj</th>
            </tr>
            {% for room in room_types_unique %}
                <tr>
                    <td>{{ room.grouper }}</td>
                    <td>
                        {% for feature in room.list.0.feature_set.all %}
                            {#            biorę tylko pierwszy pokoj a feature w bazie są rózne dla różnych pokoi#}
                            <br>{{ feature.name }}
                        {% endfor %}
                    </td>
                    <td>Cena za noc za osobę: {{ room.list.0.price }}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'new-reservation' room.list.0.id %}">Rezerwuj</a></td>
                    {% else %}
                        <td>Zaloguj się, aby zarezerwować</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    {% if premises.review_set.all %}
    <div class="container">Opinie:
        {% for review in premises.review_set.all %}
            <div class="review">
                <strong>Tytuł: {{ review.title }}</strong><br>
                <div class="review_content">Treść: {{ review.content }}</div>
                <br>
                <div class="date">Data: {{ review.date }}</div>
                <div class="rating">{{ review.score }}</div>
            </div>
          {% endfor %}
    </div>
    {% endif %}
{% endblock %}

main/templates/main/reservation_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    Ośrodek: {{ reservation.rooms.premises }}
    <br>Liczba osób w pokoju: {{ reservation.rooms.people_number }}
    <br>Cena za noc: {{ reservation.rooms.price }}
    <br>Daty: {{ reservation.start_date }} - {{ reservation.end_date }}
    <br>
    <input type="submit" value="Usuń">
    <input type="button" value="Anuluj" onclick="window.history.go(-1);">
</form>
{% endblock %}

main/templates/main/reservation_form.html
{% extends 'main/base.html' %}
{% block content %}
    <p class="error">{{ error }}</p>

<form method="post">
    {% csrf_token %}
    Ośrodek: {{ room.premises }}
    <br>Liczba osób w pokoju: {{ room.people_number }}
    <br>Cena za noc: {{ room.price }}
    {{ form.as_p }}
    <input type="submit" value="Rezerwuj">
</form>
{% endblock %}

main/templates/main/reservation_list.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <table>

        {% for reservation in reservation_list %}
            <tr>
                <td>{{ reservation.rooms.premises }}
                    <br> {{ reservation.start_date }} - {{ reservation.end_date }}</td>
                <td>
                    <a href="{% url 'edit-reservation' reservation.id %}">
                        <button>Edytuj</button>
                    </a>
                    <a href="{% url 'delete-reservation' reservation.id %}">
                        <button>Usuń</button>
                    </a>
                    {% if not reservation.review %}
                        <a href="{% url 'new-review' reservation.id %}">
                            <button>Oceń</button>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <li>Brak rezerwacji</li>
        {% endfor %}
        </tr>
    </table>
{% endblock %}

main/templates/main/reservation_update_form.html
{% extends 'main/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    Ośrodek: {{ reservation.rooms.premises }}
    <br>Liczba osób w pokoju: {{ reservation.rooms.people_number }}
    <br>Cena za noc: {{ reservation.rooms.price }}
    {{ form.as_p }}
    <input type="submit" value="Rezerwuj">
</form>
{% endblock %}

main/templates/main/review_form.html
{% extends 'main/base.html' %}
{% block content %}


<form method="post">
    {% csrf_token %}
    Ośrodek: {{ room.premises }}
    <br>Liczba osób w pokoju: {{ room.people_number }}
    <br>Cena za noc: {{ room.price }}
    {{ form.as_p }}
    <input type="submit" value="Wyślij opinię">
</form>
{% endblock %}

main/templates/main/user.html
{% extends 'main/base.html' %}
{% block content %}
    <br>Login: {{ user.username }}
    <br>Imię: {{ user.first_name }}
    <br>Nazwisko: {{ user.last_name }}
    <br>Email: {{ user.email }}
    <br><a href="{% url 'edit-user' user.id %}">Edytuj</a>
{% endblock %}

main/templates/main/user_form.html
{% extends 'main/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Wyślij">
    </form>
{% endblock %}